language: python
python:
- '3.4'
- '3.5'
script: python -m unittest
notifications:
  slack:
    secure: MxeBLKpJ8twTOkhRG287+z4iu1NYkr/eKCLnHNPW7KJ1HQor2iD/gzA28pWpPX2Sda6fmpxeQ/mT6NJsyEL32oXruHpywMehECZdMc1A+wQXGdDdgBIeqKXwD8/HBtxoe+NhZ2Ckare5mbiS3/ipdKZFdCeeGN1ZXBb1uA8VqsJcY3P1D3rK65KhXKPAXIw3cDZlzNFRz9B6+C1dlSjnr0uP919zx0rnEUqnMp3L10EIXIV12wfme0fVOk3eI9fPtIBUdgw3F30U5RxrLEDrXWCBBJfgWz57sQBHmah+CNw+bpn9aUFbR1F6pp4wBE9pKwGDbJBplJccQ9Q7/TQ5SoMqZQXFEj8ZSS97LfgDA9LYYpS1McPHgCTiwMsFMERylr85mS0vjpB993kPnD2RJx8JvKYNw7U1MUfpYouKj6YJM7zONl3k4JFuMd0BPV4uvqEwwZR9O2E4kQLf2l/9picYS8hKOiTh6lGxv2oqIHCu8B8lznHAYtUZZ9HBZIutWZBZjo392qupiUDQBf9Tf6diWGEEQ1J42TB5QijQZ9ZcBjYcFKwCo954QndfmDfL5Xv9WbhToIntysZnt8AIbqnARJkKhJosytjcisckPAQlSU2Ns4J78LVx60WyebK9LVQkE4YSrM/tMgkA/9ngmxmBxLXC8yXoJ+5ZnkHacXE=
